version: '3.8'

services:
  backend:
    build: ./Back
    container_name: back
    ports:
      - "3001:3001"

  frontend:
    build: ./Front
    container_name: my-app
    ports:
      - "8080:80"

  reverse-proxy:
    build: ./
    container_name: reverse-proxy
    ports:
      - "8100:8100"
    depends_on:
      - backend
      - frontend