services:
  backend:
    build: ./Back
    container_name: backend
    ports:
      - "3001:3001"

  frontend:
    build: ./Front
    container_name: frontend
    ports:
      - "8080:8080"

  reverse-proxy:
    build: ./
    container_name: reverse-proxy
    ports:
      - "8100:8100"
    depends_on:
      - backend
      - frontend